#!/bin/bash

cvs checkout acs-admin
cvs checkout acs-api-browser
cvs checkout acs-authentication
cvs checkout acs-automated-testing
cvs checkout acs-bootstrap-installer
cvs checkout acs-content-repository
cvs checkout acs-core-docs
cvs checkout acs-datetime
cvs checkout acs-developer-support
cvs checkout acs-events
cvs checkout acs-kernel
cvs checkout acs-lang
cvs checkout acs-mail
cvs checkout acs-mail-lite
cvs checkout acs-messaging
cvs checkout acs-reference
cvs checkout acs-service-contract
cvs checkout acs-subsite
cvs checkout acs-tcl
cvs checkout acs-templating
cvs checkout acs-workflow

cvs checkout bug-tracker
cvs checkout bulk-mail
cvs checkout chat
cvs checkout cms
cvs checkout diagram
cvs checkout ecommerce
cvs checkout events

cvs checkout intranet-amberjack
cvs checkout intranet-big-brother
cvs checkout intranet-bug-tracker
cvs checkout intranet-core
cvs checkout intranet-cost
cvs checkout intranet-crm-tracking
cvs checkout intranet-cvs-integration
cvs checkout intranet-dw-light
cvs checkout intranet-dynfield
cvs checkout intranet-exchange-rate
cvs checkout intranet-expenses
cvs checkout intranet-filestorage
cvs checkout intranet-forum
cvs checkout intranet-ganttproject
cvs checkout intranet-hr
cvs checkout intranet-invoices
cvs checkout intranet-invoices-templates
cvs checkout intranet-mail-import
cvs checkout intranet-material
cvs checkout intranet-payments
cvs checkout intranet-reporting
cvs checkout intranet-reporting-tutorial
cvs checkout intranet-search-pg
cvs checkout intranet-search-pg-files
cvs checkout intranet-security-update-client
cvs checkout intranet-simple-survey
cvs checkout intranet-timesheet2
cvs checkout intranet-timesheet2-invoices
cvs checkout intranet-timesheet2-task-popup
cvs checkout intranet-timesheet2-tasks
cvs checkout intranet-translation
cvs checkout intranet-update-client
cvs checkout intranet-wiki

cvs checkout notifications
cvs checkout ref-countries
cvs checkout ref-language
cvs checkout ref-timezones
cvs checkout ref-us-countries
cvs checkout ref-us-states
cvs checkout ref-us-zipcodes
cvs checkout search
cvs checkout simple-survey
cvs checkout wiki
cvs checkout workflow
cvs checkout xml-rpc
