#!/bin/bash

cvs checkout acs-admin
cvs checkout acs-api-browser
cvs checkout acs-authentication
cvs checkout acs-automated-testing
cvs checkout acs-bootstrap-installer
cvs checkout acs-content-repository
cvs checkout acs-core-docs
cvs checkout acs-datetime
cvs checkout acs-developer-support
cvs checkout acs-events
cvs checkout acs-kernel
cvs checkout acs-lang
cvs checkout acs-mail
cvs checkout acs-mail-lite
cvs checkout acs-messaging
cvs checkout acs-reference
cvs checkout acs-service-contract
cvs checkout acs-subsite
cvs checkout acs-tcl
cvs checkout acs-templating
cvs checkout acs-workflow

cvs checkout bulk-mail
cvs checkout chat
cvs checkout cms
cvs checkout events

cvs checkout intranet-big-brother
cvs checkout intranet-core
cvs checkout intranet-cost
cvs checkout intranet-crm-tracking
cvs checkout intranet-dw-light
cvs checkout intranet-dynfield
cvs checkout intranet-exchange-rate
cvs checkout intranet-filestorage
cvs checkout intranet-forum
cvs checkout intranet-freelance
cvs checkout intranet-freelance-invoices
cvs checkout intranet-hr
cvs checkout intranet-invoices
cvs checkout intranet-mail-import
cvs checkout intranet-material
cvs checkout intranet-payments
cvs checkout intranet-reporting
cvs checkout intranet-reporting-dashboard
cvs checkout intranet-riskmanagement
cvs checkout intranet-search-pg
cvs checkout intranet-security-update-client
cvs checkout intranet-simple-survey
cvs checkout intranet-spam
cvs checkout intranet-sql-selectors
cvs checkout intranet-timesheet
cvs checkout intranet-timesheet2
cvs checkout intranet-timesheet2-invoices
cvs checkout intranet-timesheet2-tasks
cvs checkout intranet-translation
cvs checkout intranet-trans-invoices
cvs checkout intranet-trans-quality
cvs checkout intranet-update-client
cvs checkout intranet-wiki
cvs checkout intranet-workflow

cvs checkout ref-countries
cvs checkout ref-language
cvs checkout ref-timezones
cvs checkout ref-us-counties
cvs checkout ref-us-states
cvs checkout ref-us-zipcodes

cvs checkout search
cvs checkout simple-survey
cvs checkout wiki
