#!/bin/bash

# ACS Core 5.6 version
./git-subtree acs-content-repository oacs-5-6
./git-subtree acs-reference oacs-5-6
./git-subtree intermedia-driver oacs-5-6
./git-subtree search oacs-5-6
./git-subtree acs-admin oacs-5-6
./git-subtree acs-core-docs oacs-5-6
./git-subtree acs-service-contract oacs-5-6
./git-subtree notifications oacs-5-6
./git-subtree tsearch2-driver oacs-5-6
./git-subtree acs-api-browser oacs-5-6
./git-subtree acs-kernel oacs-5-6
./git-subtree acs-subsite oacs-5-6
./git-subtree openacs-default-theme oacs-5-6
./git-subtree acs-authentication oacs-5-6
./git-subtree acs-lang oacs-5-6
./git-subtree acs-tcl oacs-5-6
./git-subtree ref-countries oacs-5-6
./git-subtree acs-automated-testing oacs-5-6
./git-subtree acs-mail-lite oacs-5-6
./git-subtree acs-templating oacs-5-6
./git-subtree ref-language oacs-5-6
./git-subtree acs-bootstrap-installer oacs-5-6
./git-subtree acs-messaging oacs-5-6
./git-subtree acs-translations oacs-5-6
./git-subtree ref-timezones oacs-5-6


# Additional packages from openacs
./git-subtree acs-datetime master
./git-subtree acs-developer-support master
./git-subtree acs-events master
./git-subtree attachments master
./git-subtree file-storage master
./git-subtree calendar master
./git-subtree categories master
./git-subtree faq master
./git-subtree general-comments master
./git-subtree mail-tracking master
./git-subtree xowiki master
./git-subtree oacs-dav master
./git-subtree rss-support master
./git-subtree xml-rpc master
./git-subtree xotcl-core master

# ]project-open[ repository
./git-subtree acs-workflow master
./git-subtree auth-ldap-adldapsearch master
./git-subtree wiki master
./git-subtree workflow master
./git-subtree acs-mail master
./git-subtree bug-tracker master
./git-subtree cms master
./git-subtree diagram master
./git-subtree intranet-big-brother master
./git-subtree intranet-bug-tracker master
./git-subtree intranet-calendar master
./git-subtree intranet-calendar-holidays master
./git-subtree intranet-confdb master
./git-subtree intranet-contacts master
./git-subtree intranet-core master
./git-subtree intranet-cost master
./git-subtree intranet-cvs-integration master
./git-subtree intranet-dw-light master
./git-subtree intranet-dynfield master
./git-subtree intranet-exchange-rate master
./git-subtree intranet-expenses master
./git-subtree intranet-expenses-workflow master
./git-subtree intranet-filestorage master
./git-subtree intranet-forum master
./git-subtree intranet-ganttproject master
./git-subtree intranet-helpdesk master
./git-subtree intranet-hr master
./git-subtree intranet-idea-management master
./git-subtree intranet-invoices master
./git-subtree intranet-invoices-templates master
./git-subtree intranet-mail-import master
./git-subtree intranet-material master
./git-subtree intranet-milestone master
./git-subtree intranet-nagios master
./git-subtree intranet-notes master
./git-subtree intranet-notes-tutorial master
./git-subtree intranet-payments master
./git-subtree intranet-release-mgmt master
./git-subtree intranet-reporting master
./git-subtree intranet-reporting-indicators master
./git-subtree intranet-reporting-tutorial master
./git-subtree intranet-resource-management master
./git-subtree intranet-rest master
./git-subtree intranet-riskmanagement master
./git-subtree intranet-rss-reader master
./git-subtree intranet-search-pg master
./git-subtree intranet-search-pg-files master
./git-subtree intranet-security-update-client master
./git-subtree intranet-soap-lite-server master
./git-subtree intranet-sysconfig master
./git-subtree intranet-simple-survey master
./git-subtree intranet-timesheet2 master
./git-subtree intranet-timesheet2-invoices master
./git-subtree intranet-timesheet2-task-popup master
./git-subtree intranet-timesheet2-tasks master
./git-subtree intranet-timesheet2-workflow master
./git-subtree intranet-tinytm master
./git-subtree intranet-trans-invoices master
./git-subtree intranet-trans-project-wizard master
./git-subtree intranet-translation master
./git-subtree intranet-ubl master
./git-subtree intranet-update-client master
./git-subtree intranet-wiki master
./git-subtree intranet-workflow master
./git-subtree intranet-xmlrpc master
