
/*
 * Business Process Definition: Duplicate Token Test (duplicate_token_test_wf)
 *
 * Auto-generated by ACS Workflow Export, version 4.3
 *
 * Context: default
 */


/*
 * Cases table
 */
create table duplicate_token_test_wf_cases (
  case_id               integer primary key
                        references wf_cases on delete cascade
);

/* 
 * Declare the object type
 */


create function inline_0 () returns integer as '
begin
    PERFORM workflow__create_workflow (
        ''duplicate_token_test_wf'', 
        ''Duplicate Token Test'', 
        ''Duplicate Token Test'', 
        ''Test workflow that will create duplicate tokens for testing a routine to delete duplicated tokens'', 
        ''duplicate_token_test_wf_cases'',
        ''case_id''
    );

    return null;

end;' language 'plpgsql';

select inline_0 ();
drop function inline_0 ();

        


/*****
 * Places
 *****/


    select workflow__add_place(
        'duplicate_token_test_wf',
        'start', 
        'Ready to Start', 
        null
    );

        

    select workflow__add_place(
        'duplicate_token_test_wf',
        'before_path_a', 
        'Ready to Path A', 
        null
    );

        

    select workflow__add_place(
        'duplicate_token_test_wf',
        'before_path_b', 
        'Ready to Path B', 
        null
    );

        

    select workflow__add_place(
        'duplicate_token_test_wf',
        'before_path_b__2', 
        'Ready to Path B - 2', 
        null
    );

        

    select workflow__add_place(
        'duplicate_token_test_wf',
        'before_end', 
        'Ready to End', 
        null
    );

        

    select workflow__add_place(
        'duplicate_token_test_wf',
        'end', 
        'Process finished', 
        null
    );

        

    select workflow__add_place(
        'duplicate_token_test_wf',
        'before_end_b', 
        'before_end_b', 
        null
    );

        
/*****
 * Roles
 *****/



	select workflow__add_role (
         'duplicate_token_test_wf',
         'start',
         'Start',
         1
    );

        

	select workflow__add_role (
         'duplicate_token_test_wf',
         'path_a',
         'Path A',
         2
    );

        

	select workflow__add_role (
         'duplicate_token_test_wf',
         'path_b',
         'Path B',
         3
    );

        

	select workflow__add_role (
         'duplicate_token_test_wf',
         'path_b__2',
         'Path B - 2',
         4
    );

        

	select workflow__add_role (
         'duplicate_token_test_wf',
         'end',
         'End',
         5
    );

        

/*****
 * Transitions
 *****/



	select workflow__add_transition (
         'duplicate_token_test_wf',
         'start',
         'Start',
         'start',
         1,
         'user'
	);
	
        

	select workflow__add_transition (
         'duplicate_token_test_wf',
         'path_a',
         'Path A',
         'path_a',
         2,
         'user'
	);
	
        

	select workflow__add_transition (
         'duplicate_token_test_wf',
         'path_b',
         'Path B',
         'path_b',
         3,
         'user'
	);
	
        

	select workflow__add_transition (
         'duplicate_token_test_wf',
         'path_b__2',
         'Path B - 2',
         'path_b__2',
         4,
         'user'
	);
	
        

	select workflow__add_transition (
         'duplicate_token_test_wf',
         'end',
         'End',
         'end',
         5,
         'user'
	);
	
        

/*****
 * Arcs
 *****/



	select workflow__add_arc (
         'duplicate_token_test_wf',
         'end',
         'before_end',
         'in',
         '',
         '',
         ''
	);

        

	select workflow__add_arc (
         'duplicate_token_test_wf',
         'end',
         'end',
         'out',
         '',
         '',
         ''
	);

        

	select workflow__add_arc (
         'duplicate_token_test_wf',
         'end',
         'before_end_b',
         'in',
         '',
         '',
         ''
	);

        

	select workflow__add_arc (
         'duplicate_token_test_wf',
         'path_a',
         'start',
         'out',
         '#',
         '',
         'Not Path A OK'
	);

        

	select workflow__add_arc (
         'duplicate_token_test_wf',
         'path_a',
         'before_end_b',
         'out',
         'wf_callback__guard_attribute_true',
         'path_a_path_a_ok_p',
         'OK'
	);

        

	select workflow__add_arc (
         'duplicate_token_test_wf',
         'path_a',
         'before_path_a',
         'in',
         '',
         '',
         ''
	);

        

	select workflow__add_arc (
         'duplicate_token_test_wf',
         'path_b',
         'before_path_b',
         'in',
         '',
         '',
         ''
	);

        

	select workflow__add_arc (
         'duplicate_token_test_wf',
         'path_b',
         'start',
         'out',
         '#',
         '',
         'Not Path B OK'
	);

        

	select workflow__add_arc (
         'duplicate_token_test_wf',
         'path_b',
         'before_path_b__2',
         'out',
         'wf_callback__guard_attribute_true',
         'path_b_path_b_ok_p',
         'Path B OK'
	);

        

	select workflow__add_arc (
         'duplicate_token_test_wf',
         'path_b__2',
         'before_path_b__2',
         'in',
         '',
         '',
         ''
	);

        

	select workflow__add_arc (
         'duplicate_token_test_wf',
         'path_b__2',
         'before_end',
         'out',
         '',
         '',
         ''
	);

        

	select workflow__add_arc (
         'duplicate_token_test_wf',
         'start',
         'before_path_b',
         'out',
         '',
         '',
         ''
	);

        

	select workflow__add_arc (
         'duplicate_token_test_wf',
         'start',
         'start',
         'in',
         '',
         '',
         ''
	);

        

	select workflow__add_arc (
         'duplicate_token_test_wf',
         'start',
         'before_path_a',
         'out',
         '',
         '',
         ''
	);

        

/*****
 * Attributes
 *****/



    select workflow__create_attribute(
        'duplicate_token_test_wf',
        'path_a_path_a_ok_p',
        'boolean',
        'Path A OK',
	null,
	null,
	null,
        't',
	1,
	1,
	null,
	'generic'
    );

        

	select workflow__add_trans_attribute_map(
        	'duplicate_token_test_wf', 
        	'path_a',
        	'path_a_path_a_ok_p',
        	1
    );

        

    select workflow__create_attribute(
        'duplicate_token_test_wf',
        'path_b_path_b_ok_p',
        'boolean',
        'Path B OK',
	null,
	null,
	null,
        't',
	1,
	1,
	null,
	'generic'
    );

        

	select workflow__add_trans_attribute_map(
        	'duplicate_token_test_wf', 
        	'path_b',
        	'path_b_path_b_ok_p',
        	1
    );

        
/*****
 * Transition-role-assignment-map
 *****/



/*
 * Context/Transition info
 * (for context = default)
 */

insert into wf_context_transition_info
(context_key,
 workflow_key,
 transition_key,
 estimated_minutes,
 instructions,
 enable_callback,
 enable_custom_arg,
 fire_callback,
 fire_custom_arg,
 time_callback,
 time_custom_arg,
 deadline_callback,
 deadline_custom_arg,
 deadline_attribute_name,
 hold_timeout_callback,
 hold_timeout_custom_arg,
 notification_callback,
 notification_custom_arg,
 unassigned_callback,
 unassigned_custom_arg)
values
('default',
 'duplicate_token_test_wf',
 'path_a',
 5,
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '');

insert into wf_context_transition_info
(context_key,
 workflow_key,
 transition_key,
 estimated_minutes,
 instructions,
 enable_callback,
 enable_custom_arg,
 fire_callback,
 fire_custom_arg,
 time_callback,
 time_custom_arg,
 deadline_callback,
 deadline_custom_arg,
 deadline_attribute_name,
 hold_timeout_callback,
 hold_timeout_custom_arg,
 notification_callback,
 notification_custom_arg,
 unassigned_callback,
 unassigned_custom_arg)
values
('default',
 'duplicate_token_test_wf',
 'path_b',
 5,
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '');

insert into wf_context_transition_info
(context_key,
 workflow_key,
 transition_key,
 estimated_minutes,
 instructions,
 enable_callback,
 enable_custom_arg,
 fire_callback,
 fire_custom_arg,
 time_callback,
 time_custom_arg,
 deadline_callback,
 deadline_custom_arg,
 deadline_attribute_name,
 hold_timeout_callback,
 hold_timeout_custom_arg,
 notification_callback,
 notification_custom_arg,
 unassigned_callback,
 unassigned_custom_arg)
values
('default',
 'duplicate_token_test_wf',
 'path_b__2',
 5,
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '');

insert into wf_context_transition_info
(context_key,
 workflow_key,
 transition_key,
 estimated_minutes,
 instructions,
 enable_callback,
 enable_custom_arg,
 fire_callback,
 fire_custom_arg,
 time_callback,
 time_custom_arg,
 deadline_callback,
 deadline_custom_arg,
 deadline_attribute_name,
 hold_timeout_callback,
 hold_timeout_custom_arg,
 notification_callback,
 notification_custom_arg,
 unassigned_callback,
 unassigned_custom_arg)
values
('default',
 'duplicate_token_test_wf',
 'end',
 5,
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '');

insert into wf_context_transition_info
(context_key,
 workflow_key,
 transition_key,
 estimated_minutes,
 instructions,
 enable_callback,
 enable_custom_arg,
 fire_callback,
 fire_custom_arg,
 time_callback,
 time_custom_arg,
 deadline_callback,
 deadline_custom_arg,
 deadline_attribute_name,
 hold_timeout_callback,
 hold_timeout_custom_arg,
 notification_callback,
 notification_custom_arg,
 unassigned_callback,
 unassigned_custom_arg)
values
('default',
 'duplicate_token_test_wf',
 'start',
 5,
 '',
 'im_workflow__delete_all_other_tokens',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '');



/*
 * Context/Role info
 * (for context = default)
 */



/*
 * Context Task Panels
 * (for context = default)
 */


commit;

