
/*
 * Business Process Definition: Quick Ticket Workflow (ticket_quick_wf)
 *
 * Auto-generated by ACS Workflow Export, version 4.3
 *
 * Context: default
 */


/*
 * Cases table
 */
create table ticket_quick_wf_cases (
  case_id               integer primary key
                        references wf_cases on delete cascade
);

/* 
 * Declare the object type
 */


create function inline_0 () returns integer as '
begin
    PERFORM workflow__create_workflow (
        ''ticket_quick_wf'', 
        ''Quick Ticket Workflow'', 
        ''Quick Ticket Workflow'', 
        ''Fast workflow which allows the helpdesk to quickly work on a ticket or put it back into the queue again.'', 
        ''ticket_quick_wf_cases'',
        ''case_id''
    );

    return null;

end;' language 'plpgsql';

select inline_0 ();
drop function inline_0 ();

        


/*****
 * Places
 *****/


    select workflow__add_place(
        'ticket_quick_wf',
        'start', 
        'Ready to Open Ticket', 
        null
    );

        

    select workflow__add_place(
        'ticket_quick_wf',
        'before_execute_ticket', 
        'Ready to Execute Ticket', 
        null
    );

        

    select workflow__add_place(
        'ticket_quick_wf',
        'before_close_ticket', 
        'Ready to Close Ticket', 
        null
    );

        

    select workflow__add_place(
        'ticket_quick_wf',
        'end', 
        'Process finished', 
        null
    );

        
/*****
 * Roles
 *****/



	select workflow__add_role (
         'ticket_quick_wf',
         'open_ticket',
         'Open Ticket',
         1
    );

        

	select workflow__add_role (
         'ticket_quick_wf',
         'execute_ticket',
         'Execute Ticket',
         2
    );

        

	select workflow__add_role (
         'ticket_quick_wf',
         'close_ticket',
         'Close Ticket',
         3
    );

        

/*****
 * Transitions
 *****/



	select workflow__add_transition (
         'ticket_quick_wf',
         'open_ticket',
         'Open Ticket',
         'open_ticket',
         1,
         'user'
	);
	
        

	select workflow__add_transition (
         'ticket_quick_wf',
         'execute_ticket',
         'Execute Ticket',
         'execute_ticket',
         2,
         'user'
	);
	
        

	select workflow__add_transition (
         'ticket_quick_wf',
         'close_ticket',
         'Close Ticket',
         'close_ticket',
         3,
         'automatic'
	);
	
        

/*****
 * Arcs
 *****/



	select workflow__add_arc (
         'ticket_quick_wf',
         'close_ticket',
         'before_close_ticket',
         'in',
         '',
         '',
         ''
	);

        

	select workflow__add_arc (
         'ticket_quick_wf',
         'close_ticket',
         'end',
         'out',
         '',
         '',
         ''
	);

        

	select workflow__add_arc (
         'ticket_quick_wf',
         'execute_ticket',
         'before_close_ticket',
         'out',
         'wf_callback__guard_attribute_true',
         'execute_ticket_did_you_complete_the_work_on_this_ticket_p',
         'Did you complete the work on this ticket'
	);

        

	select workflow__add_arc (
         'ticket_quick_wf',
         'execute_ticket',
         'before_execute_ticket',
         'out',
         '#',
         '',
         'Not Did you complete the work on this ticket'
	);

        

	select workflow__add_arc (
         'ticket_quick_wf',
         'execute_ticket',
         'before_execute_ticket',
         'in',
         '',
         '',
         ''
	);

        

	select workflow__add_arc (
         'ticket_quick_wf',
         'open_ticket',
         'start',
         'in',
         '',
         '',
         ''
	);

        

	select workflow__add_arc (
         'ticket_quick_wf',
         'open_ticket',
         'before_execute_ticket',
         'out',
         '',
         '',
         ''
	);

        

/*****
 * Attributes
 *****/



    select workflow__create_attribute(
        'ticket_quick_wf',
        'execute_ticket_did_you_complete_the_work_on_this_ticket_p',
        'boolean',
        'Did you complete the work on this ticket',
	null,
	null,
	null,
        't',
	1,
	1,
	null,
	'generic'
    );

        

	select workflow__add_trans_attribute_map(
        	'ticket_quick_wf', 
        	'execute_ticket',
        	'execute_ticket_did_you_complete_the_work_on_this_ticket_p',
        	1
    );

        
/*****
 * Transition-role-assignment-map
 *****/



/*
 * Context/Transition info
 * (for context = default)
 */

insert into wf_context_transition_info
(context_key,
 workflow_key,
 transition_key,
 estimated_minutes,
 instructions,
 enable_callback,
 enable_custom_arg,
 fire_callback,
 fire_custom_arg,
 time_callback,
 time_custom_arg,
 deadline_callback,
 deadline_custom_arg,
 deadline_attribute_name,
 hold_timeout_callback,
 hold_timeout_custom_arg,
 notification_callback,
 notification_custom_arg,
 unassigned_callback,
 unassigned_custom_arg)
values
('default',
 'ticket_quick_wf',
 'close_ticket',
 null,
 '',
 'im_workflow__set_object_status_id',
 '30001',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '');



/*
 * Context/Role info
 * (for context = default)
 */



/*
 * Context Task Panels
 * (for context = default)
 */


commit;

